{{ if and .Values.kubediag.operations.podListCollector.enabled .Values.kubediag.operations.coreFileProfiler.enabled }}
apiVersion: diagnosis.kubediag.org/v1
kind: OperationSet
metadata:
  name: core-file-operationset
spec:
  adjacencyList:
    - id: 0
      to:
        - 1
        - 2
    - id: 1
      operation: pod-list-collector
      to:
        - 2
    - id: 2
      operation: core-file-profiler
{{ end }}
