{{ if .Values.kubediag.operations.elasticsearchCollector.enabled }}
apiVersion: diagnosis.kubediag.org/v1
kind: OperationSet
metadata:
  name: elasticsearch-collector
spec:
  adjacencyList:
  - id: 0
    to:
    - 1
  - id: 1
    operation: elasticsearch-collector
{{ end }}
