apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: kubediag
    mode: master
  name: kubediag-master
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.master.port }}
    targetPort: http
  selector:
    control-plane: kubediag
    mode: master
  type: {{ .Values.service.master.type }}
