{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: kubediag
    mode: master
  name: kubediag-master-metrics-monitor
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.args.master.metricsPort }}
    targetPort: metrics
  selector:
    control-plane: kubediag
    mode: master
  type: ClusterIP
{{- end }}
